name: Build / Test
on:
  push:
    branches:
      test-actions
    #pull_request:


jobs:
  run-tests:
    name: Run All Tests
    runs-on: macos-latest 
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 14.x ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate .env file
        uses: project-vagabond/template-action@v1
        with:
          template: .templates/.env.template
          output: .env
          vars: |
            {
              "API_HOST": "${{ secrets.API_HOST }}",
              "SAFETYNET_KEY": "${{ secrets.SAFETYNET_KEY }}"
            }

      - name: Generate iOS AuthKey
        run: echo "${{ secrets.IOS_AUTH_KEY }}" > "ios/AuthKey_${{ secrets.IOS_AUTH_KEY_ID }}.p8"

      - name: Generate iOS Signing Key
        run: echo "${{ secrets.SIGNING_KEY_P12_B64 }}" | base64 -d > "ios/NY COVID Proximity.key.p12"

      - name: Generate iOS proximity config DEV
        uses: project-vagabond/template-action@v1
        with:
          template: .templates/ios/firebase/development/GoogleService-Info.plist.template
          output: ios/firebase/development/GoogleService-Info.plist
          vars: |
            {
              "IOS_CLIENT_ID": "${{ secrets.PROX_IOS_CLIENT_ID_DEV}}",
              "IOS_CLIENT_ID_REV": "${{ secrets.PROX_IOS_CLIENT_ID_REV_DEV}}",
              "IOS_API_KEY": "${{ secrets.PROX_IOS_API_KEY_DEV}}",
              "ANDROID_CLIENT_ID": "${{ secrets.PROX_ANDROID_CLIENT_ID_DEV}}",
              "ANDROID_API_KEY": "${{ secrets.PROX_ANDROID_API_KEY_DEV}}",
              "GCM_SENDER_ID": "${{ secrets.PROX_GCM_SENDER_ID_DEV}}",
              "BUNDLE_ID": "${{ secrets.PROX_BUNDLE_ID_DEV}}",
              "PROJECT_ID": "${{ secrets.PROX_PROJECT_ID_DEV}}",
              "STORAGE_BUCKET": "${{ secrets.PROX_STORAGE_BUCKET_DEV}}",
              "IOS_GOOGLE_APP_ID": "${{ secrets.PROX_IOS_GOOGLE_APP_ID_DEV}}",
              "ANDROID_GOOGLE_APP_ID": "${{ secrets.PROX_ANDROID_GOOGLE_APP_ID_DEV}}",
              "DATABASE_URL": "${{ secrets.PROX_DATABASE_URL_DEV}}"
            }

      - name: Generate iOS proximity config PROD
        uses: project-vagabond/template-action@v1
        with:
          template: .templates/ios/firebase/production/GoogleService-Info.plist.template
          output: ios/firebase/production/GoogleService-Info.plist
          vars: |
            {
              "IOS_CLIENT_ID": "${{ secrets.PROX_IOS_CLIENT_ID_PROD}}",
              "IOS_CLIENT_ID_REV": "${{ secrets.PROX_IOS_CLIENT_ID_REV_PROD}}",
              "IOS_API_KEY": "${{ secrets.PROX_IOS_API_KEY_PROD}}",
              "ANDROID_CLIENT_ID": "${{ secrets.PROX_ANDROID_CLIENT_ID_PROD}}",
              "ANDROID_API_KEY": "${{ secrets.PROX_ANDROID_API_KEY_PROD}}",
              "GCM_SENDER_ID": "${{ secrets.PROX_GCM_SENDER_ID_PROD}}",
              "BUNDLE_ID": "${{ secrets.PROX_BUNDLE_ID_PROD}}",
              "PROJECT_ID": "${{ secrets.PROX_PROJECT_ID_PROD}}",
              "STORAGE_BUCKET": "${{ secrets.PROX_STORAGE_BUCKET_PROD}}",
              "IOS_GOOGLE_APP_ID": "${{ secrets.PROX_IOS_GOOGLE_APP_ID_PROD}}",
              "ANDROID_GOOGLE_APP_ID": "${{ secrets.PROX_ANDROID_GOOGLE_APP_ID_PROD}}",
              "DATABASE_URL": "${{ secrets.PROX_DATABASE_URL_PROD}}"
            }

      - name: Generate Android proximity config DEV
        uses: project-vagabond/template-action@v1
        with:
          template: .templates/android/app/src/debug/google-services.json.template
          output: android/app/src/debug/google-services.json
          vars: |
            {
              "IOS_CLIENT_ID": "${{ secrets.PROX_IOS_CLIENT_ID_DEV}}",
              "IOS_CLIENT_ID_REV": "${{ secrets.PROX_IOS_CLIENT_ID_REV_DEV}}",
              "IOS_API_KEY": "${{ secrets.PROX_IOS_API_KEY_DEV}}",
              "ANDROID_CLIENT_ID": "${{ secrets.PROX_ANDROID_CLIENT_ID_DEV}}",
              "ANDROID_API_KEY": "${{ secrets.PROX_ANDROID_API_KEY_DEV}}",
              "GCM_SENDER_ID": "${{ secrets.PROX_GCM_SENDER_ID_DEV}}",
              "BUNDLE_ID": "${{ secrets.PROX_BUNDLE_ID_DEV}}",
              "PROJECT_ID": "${{ secrets.PROX_PROJECT_ID_DEV}}",
              "STORAGE_BUCKET": "${{ secrets.PROX_STORAGE_BUCKET_DEV}}",
              "IOS_GOOGLE_APP_ID": "${{ secrets.PROX_IOS_GOOGLE_APP_ID_DEV}}",
              "ANDROID_GOOGLE_APP_ID": "${{ secrets.PROX_ANDROID_GOOGLE_APP_ID_DEV}}",
              "DATABASE_URL": "${{ secrets.PROX_DATABASE_URL_DEV}}"
            }

      - name: Generate iOS proximity config PROD
        uses: project-vagabond/template-action@v1
        with:
          template: .templates/android/app/src/release/google-services.json.template
          output: android/app/src/release/google-services.json
          vars: |
            {
              "IOS_CLIENT_ID": "${{ secrets.PROX_IOS_CLIENT_ID_PROD}}",
              "IOS_CLIENT_ID_REV": "${{ secrets.PROX_IOS_CLIENT_ID_REV_PROD}}",
              "IOS_API_KEY": "${{ secrets.PROX_IOS_API_KEY_PROD}}",
              "ANDROID_CLIENT_ID": "${{ secrets.PROX_ANDROID_CLIENT_ID_PROD}}",
              "ANDROID_API_KEY": "${{ secrets.PROX_ANDROID_API_KEY_PROD}}",
              "GCM_SENDER_ID": "${{ secrets.PROX_GCM_SENDER_ID_PROD}}",
              "BUNDLE_ID": "${{ secrets.PROX_BUNDLE_ID_PROD}}",
              "PROJECT_ID": "${{ secrets.PROX_PROJECT_ID_PROD}}",
              "STORAGE_BUCKET": "${{ secrets.PROX_STORAGE_BUCKET_PROD}}",
              "IOS_GOOGLE_APP_ID": "${{ secrets.PROX_IOS_GOOGLE_APP_ID_PROD}}",
              "ANDROID_GOOGLE_APP_ID": "${{ secrets.PROX_ANDROID_GOOGLE_APP_ID_PROD}}",
              "DATABASE_URL": "${{ secrets.PROX_DATABASE_URL_PROD}}"
            }
      - run: cat ios/firebase/development/GoogleService-Info.plist




#      - name: Running tests with node ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#
#      - name: Setup Yarn Cache
#        uses: bahmutov/npm-install@v1.4.3
#        with:
#          useLockFile: true
#
#      - name: Yarn Install
#        run: yarn install --frozen-lockfile
#
#      - name: Setup CocoaPods Cache
#        uses: actions/cache@v1
#        with:
#          path: ios/Pods
#          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-pods-
#
#      - name: Install CocoaPods Dependencies
#        run: cd ios && pod install
#
#      - name: iOS Build
#        run: cd ios && fastlane internal
#
#      - name: Android Build
#        run: cd android && fastlane internal
#
